config/routes.rb
Students::Application.routes.draw do
  
  resources :users

  resources :courses do
    member do
      get :roll
    end
  end

  resources :students do
    resources :awards

    member do
      get :courses
      post :course_add
      post :course_remove
    end

  end

  match "/auth/:provider/callback" => "sessions#create"

  match "/signout" => "sessions#destroy", :as => :signout

   root :to => 'students#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user


  private

  def current_user
  	if session[:user_id]
       @current_user ||= User.find(session[:user_id])
    else
    	@current_user = nil
    end
  end

  def check_login
  	unless authorized?
  		redirect_to "/auth/identity"
  	end
  end

  def logged_in?
  	if session[:user_id]
  		return true
  	else
  		return false
  	end
  end

  protected

  def authorized?
  	logged_in? && (request.get? || current_user.admin?)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_authentication.html.erb
<p>
	<% if current_user %>
	  Welcome <%= current_user.name %>!
	  | <%= link_to "Sign Out", signout_path %>
	<% else %>
	<%= link_to "Log in", "/auth/identity" %> |
	<%= link_to "Register", "/auth/identity/register" %>
	<% end %>
</p>
<hr/>

app/views/application/_navigation.html.erb
<p>
	<%= link_to "Students", students_url %> | 
	<%= link_to "Courses", courses_url %>
</p>

<hr/>